### ISSUE TITLE
Image is slightly different from docker image?

### ISSUE THREAD

**Issue by JohanEngelen** [jirutka/setup-alpine#16]
Thanks for this project! It is really useful and easy to use.

However, I'm having issues where local testing with a docker image (e.g. alpine:latest, or alpine:3.20.1) is behaving different than the image in a Github action.
In particular, `ninja` appears missing in the github action image. (and installing with `apk add ninja-is-really-ninja` does not help)

How do I locally get the same image as in GHA ?

**Comment by JohanEngelen** [comment]
To reproduce, this is my .yml file:
```yaml
name: Alpine Linux (musl libc)
on:
  - pull_request
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Alpine Linux (musl libc)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 50

      - name: Setup latest Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          branch: v3.20
          packages: ninja

      - name: Test ninja
        run: |
          ninja --version
```
