### ISSUE TITLE
Does not work in unpriveleged Docker-based runners

### ISSUE THREAD

**Issue by joeyparrish** [jirutka/setup-alpine#18]
Using bind mounts doesn't work in unprivileged Docker-based runners, such as the self-hosted runners I'm using.

I'm trying https://github.com/proot-me/PRoot/ as an alternative to bind-mounts and chroot.  PRoot can do the same things in userspace, which may make setup-alpine more compatible with self-hosted, Docker-based runners like mine.

**Comment by jirutka** [comment]
Does it actually work? I tried PRoot once and it didn’t work on Alpine.

**Comment by joeyparrish** [comment]
I never got everything completely working with proot, and I gave up on it.  I eventually gave up on setup-alpine, too.

I wound up using GitHub Actions builtin Docker image support, with some carefully-crafted bind mounts such that the outer docker (my self-hosted runner) and the inner dockers (images in the workflow) all map certain folders to the same places on the host filesystem (actual machine).  It doesn't work with multiple runner instances on the same host, though.

Here are the details of what eventually worked for me.

In [my workflow](https://github.com/shaka-project/static-ffmpeg-binaries/blob/main/.github/workflows/build.yaml):

```
    name: Build ${{ matrix.os_name }} ${{ matrix.target_arch }} ${{ matrix.container }}
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.container }}
      # Access to the host filesystem is required to patch the environment for
      # Alpine Linux support.  See the first Alpine step below for details.
      volumes:
        - /:/host

# ... later ...

    steps:
      - name: Patch native Alpine NodeJS into Runner environment
        if: startsWith(matrix.container, 'alpine')
        run: |
          apk add nodejs
          sed -i "s:^ID=alpine:ID=NotpineForGHA:" /etc/os-release
          # The first path here is for GitHub-hosted workflows, while the
          # second path is correct for our self-hosted workflows using the
          # myoung34/github-runner container.  The commands that follow this
          # are correct so long as one of these paths exists.
          cd /host/home/runner/runners/*/externals/ || cd /host/actions-runner/externals
          rm -rf node20/*
          mkdir node20/bin
          ln -s /usr/bin/node node20/bin/node
        shell: sh  # No bash in Alpine by default

      - name: Install Alpine Linux deps
        if: startsWith(matrix.container, 'alpine')
        run: apk add bash npm sudo
        shell: sh  # No bash in Alpine until after this command
```

My self-hosted runner is based on https://github.com/myoung34/docker-github-actions-runner via https://github.com/shaka-project/shaka-lab/tree/main/shaka-lab-github-runner on an Ubuntu arm64 host in the cloud.  The critical setup for docker volumes on the host is here:

https://github.com/shaka-project/shaka-lab/blob/9e39f8a8ba62f98c5117d06ce290515c0727c94b/shaka-lab-github-runner/linux/start-runner.sh#L100-L139

The mess about "EXTERNALS" below supports the node hack in the workflow above.

```sh
RUNNER_WORKDIR=/home/runner/work

# Add extra arguments necessary for nested containers, if requested.
if [[ "$SUPPORT_NESTED_CONTAINERS" == "true" ]]; then
  # To support nested containers in self-hosted workflows, certain folders
  # expected by GitHub Actions must be consistently mapped from the outer host
  # to the first container.  To keep workflows ephemeral, we also wipe these
  # before every run.
  MAPPED_FOLDERS=(
    $RUNNER_WORKDIR
    /opt/hostedtoolcache
  )
  for i in "${MAPPED_FOLDERS[@]}"; do
    rm -rf "$i"
    mkdir -p "$i"
    extra_docker_args+=(--mount type=bind,src="$i",dst="$i")
  done

  # This folder already exists inside the container image, but we want to keep
  # our own copy of it at the host level.  This will allow it to be correctly
  # mapped to nested containers, and modified if necessary.
  EXTERNALS=/actions-runner/externals
  rm -rf "$EXTERNALS"
  mkdir -p "$EXTERNALS"

  # Create a temporary docker container to extract these files.
  docker container create --name "$CONTAINER_NAME" "$DOCKER_IMAGE"

  # Copy "$EXTERNALS" itself from the container into the local parent of the
  # same.  This is because "docker cp" doesn't do wildcards, so you can't copy
  # "e/* e/".
  docker cp "$CONTAINER_NAME":"$EXTERNALS" "$EXTERNALS"/..

  # Clean up the temporary container.
  docker container rm "$CONTAINER_NAME"

  # Create a special mount for this folder.
  extra_docker_args+=(--mount type=bind,src="$EXTERNALS",dst="$EXTERNALS",ro)

  # Create a special bind for the docker socket.
  extra_docker_args+=(-v /var/run/docker.sock:/var/run/docker.sock)
fi
```

I hope this is helpful to someone.  I'm going to close this issue now, since I no longer care about setup-alpine.
